# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc316eafabc35c848f90213784490b9ebb1cf9751f428df38857beb1d9014035085ddd02c819fab635a3999178308e5de33636ba6b9b809d537b8a68cd8355dc

test:
  secret_key_base: abbd3384dd31e23fb02f3f797e85df8564eb767a6382f9ac6b8917c48f3ae2982e1354ae9b696ae45c353a273cd7eef69f7bf565b71f921295fc662589919a4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
